config/routes.rb
DadelmoCoffee::Application.routes.draw do

  root :to => 'sessions#new'

  get "account/show"

  get "sessions/new"

  resources :customer_orders

  resources :orders

  resources :products

  resources :users

  resources :roles

  resources :sessions, :only => [:new, :create, :destroy]

  match '/add_item', :to => 'customer_orders#add_item'
  match '/delete_item', :to => 'customer_orders#delete_item'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/admin_panel', :to => 'admin#index'

end

app/models/customer_order.rb
class CustomerOrder < ActiveRecord::Base
  validates_uniqueness_of :user_id, :scope => [:order_id]
  has_many :customer_order_line_products
  belongs_to :user
  belongs_to :order
end

app/controllers/customer_orders_controller.rb
class CustomerOrdersController < ApplicationController
  # GET /customer_orders
  # GET /customer_orders.xml
  def index
    @customer_orders = CustomerOrder.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @customer_orders }
    end
  end

  # GET /customer_orders/1
  # GET /customer_orders/1.xml
  def show
    @customer_order = CustomerOrder.find(params[:id])
    @total = @customer_order.customer_order_line_products.map(&:price_per_item_in_cents).sum

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @customer_order }
    end
  end

  # GET /customer_orders/new
  # GET /customer_orders/new.xml
  def new
    @customer_order = CustomerOrder.new


    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @customer_order }
    end
  end

  # GET /customer_orders/1/edit
  def edit
    @customer_order = CustomerOrder.find(params[:id])
    @products = Product.where(:active => true).sort{|p, a| p.display_name <=> a.display_name }
    @total = @customer_order.customer_order_line_products.map(&:price_per_item_in_cents).sum
  end

  # POST /customer_orders
  # POST /customer_orders.xml
  def create
    @customer_order = CustomerOrder.new(params[:customer_order])
    @customer_order.user = signed_in_user
    respond_to do |format|
      if @customer_order.save
        format.html { redirect_to :action => 'edit', :id => @customer_order.id, :notice => 'Customer order was successfully created.' }
        format.xml  { render :xml => @customer_order, :status => :created, :location => @customer_order }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @customer_order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /customer_orders/1
  # PUT /customer_orders/1.xml
  def update
    @customer_order = CustomerOrder.find(params[:id])

    respond_to do |format|
      if @customer_order.update_attributes(params[:customer_order])
        format.html { redirect_to(@customer_order, :notice => 'Customer order was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @customer_order.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def add_item
    @customer_order = CustomerOrder.find(params[:customer_order][:id])
    @total = @customer_order.customer_order_line_products.map(&:price_per_item_in_cents).sum
    if params[:p_qty].blank?
      redirect_to edit_customer_order_path(@customer_order)  
      return 
    end    
    if params[:p_qty].to_i.nil?
      redirect_to edit_customer_order_path(@customer_order)  
      return 
    end    
    product = Product.find(params[:p_id])
    cid = @customer_order.id
    pid = params[:p_id]
    pqty = params[:p_qty]
    price = product.price_in_cents
    colp = CustomerOrderLineProduct.where(:customer_order_id => cid, :product_id => pid).first
    if colp.nil?
      colp = CustomerOrderLineProduct.new ({
        :customer_order_id => cid,
        :product_id => pid,
        :qty => pqty,
        :price_per_item_in_cents => price*pqty.to_i
      })
    else
      colp.qty = colp.qty + pqty.to_i
      colp.price_per_item_in_cents = colp.product.price_in_cents * colp.qty
    end
    colp.save!

    @customer_order = CustomerOrder.find(params[:customer_order][:id])
    @total = @customer_order.customer_order_line_products.map(&:price_per_item_in_cents).sum
    respond_to do |format|
      format.html { redirect_to edit_customer_order_path(@customer_order)}
      format.js
    end
    
     
  end

  def delete_item
    cid = params[:customer_order][:id]
    pid =  params[:customer_order][:p_id]
    @colp = CustomerOrderLineProduct.where(:customer_order_id => cid, :product_id => pid).first


    @colp.destroy unless @colp.nil? 
    @customer_order = CustomerOrder.find(params[:customer_order][:id])
    @total = @customer_order.customer_order_line_products.map(&:price_per_item_in_cents).sum
    respond_to do |format|
      format.html { redirect_to edit_customer_order_path(CustomerOrder.find params[:customer_order][:id]) }
      format.js
    end
  end


  # DELETE /customer_orders/1
  # DELETE /customer_orders/1.xml
  def destroy
    @customer_order = CustomerOrder.find(params[:id])
    @customer_order.destroy

    respond_to do |format|
      format.html { redirect_to(customer_orders_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/customer_orders_helper.rb
module CustomerOrdersHelper
end

app/views/customer_orders/_form.html.erb
  <% if @customer_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer_order.errors.count, "error") %> prohibited this customer_order from being saved:</h2>

      <ul>
      <% @customer_order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    
  <% end %>


<p> Orden a pedirse el día <%= @customer_order.order.order_date %> </p> 
<p> Entrega tentativa: <%= @customer_order.order.delivery_date %> </p> 
<%= form_for(:customer_order, :url => add_item_path, :remote => true) do |f| %>
  <%= f.hidden_field :id, :value => @customer_order.id %>

 <br />
 <div class="field">
  <%= select_tag :p_id, options_from_collection_for_select(@products, :id, :display_name) %>

  <%= number_field_tag :p_qty, nil, :placeholder => 'Cantidad', :autocomplete => 'off', :min => 0 %>

    <%= f.submit "Agregar cápsulas" %>
<% end %>
  </div>

<div id="items_table">
<%= render 'order_table' %>
<div>

app/views/customer_orders/_order_table.html.erb
<% unless @customer_order.customer_order_line_products.empty? %>
<table>
 <thead>
  <tr>
    <th>Cápsula</th>
    <th>Cantidad</th>
    <th>Precio</th>
    <th></th>
  </tr>
 </thead>
 <tbody>
<% @customer_order.customer_order_line_products.each do |colp| %>

  <tr id="<%= "item_#{colp.id}" %>">
	<td><%= "#{colp.product.name}" %></td> 
	<td><%= "#{colp.qty}" %></td> 
	<td><%= "#{(colp.price_per_item_in_cents).to_f/100}€" %></td> 

	<td>
    <%= form_for(:customer_order, :url => delete_item_path, :remote => true ) do |fdel| %>
      <%= fdel.hidden_field :id, :value => @customer_order.id %>
      <%= fdel.hidden_field :p_id, :value => colp.product_id %>
      <%= fdel.submit "Borrar" %></td> 
	  <% end %>
  </td>
	
  </tr>
<% end %>
 </tbody>
 <tfoot>
  <tr>
    <td colspan="4">
      Total <%= "#{@total.to_f/100}€" %>
    </td>
  </tr>
 </tfoot>
</table>
<% end %>

app/views/customer_orders/add_item.js.erb
jQuery('#p_qty').attr('value', '');

jQuery('#items_table').html('<%= escape_javascript(render 'order_table') %>');

app/views/customer_orders/delete_item.js.erb
jQuery('#<%= "item_#{@colp.id}" %>').fadeOut(500, function() { 
	jQuery('#items_table').html('<%= escape_javascript(render 'order_table') %>')}
	);

app/views/customer_orders/edit.html.erb
<h2>Editar pedido</h2>

<%= render 'form' %>

app/views/customer_orders/index.html.erb
<h1>Listing customer_orders</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customer_orders.each do |customer_order| %>
  <tr>
    <td><%= link_to 'Show', customer_order %></td>
    <td><%= link_to 'Edit', edit_customer_order_path(customer_order) %></td>
    <td><%= link_to 'Destroy', customer_order, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Customer order', new_customer_order_path %>

app/views/customer_orders/new.html.erb
<h1>New customer_order</h1>

<%= render 'form' %>

<%= link_to 'Back', customer_orders_path %>

app/views/customer_orders/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Orden día <%= @customer_order.order.order_date %> </h2>

<p>User <%= @customer_order.user.email unless @customer_order.user.nil? %></p>

<table>
  <thead>
	<tr>
		<th>Cápsula</th>
		<th>Cantidad</th>
		<th>Precio</th>		
	</tr>
  </thead>
  <tbody>
<% @customer_order.customer_order_line_products.each do |p| %>
	<tr>
		<td><%= p.product.name %></td>
		<td><%= p.qty %></td>
		<td><%= "#{p.price_per_item_in_cents/100.0}€" %></td>
	</tr>
<% end %>
  </tbody>
  <tfoot>
  	<tr>
  		<td colspan='3'>Total <%= "#{@total.to_f/100}€" %></td>
  	</tr>
  </tfoot>
<table>


<% if is_admin? %>
	<%= link_to 'Edit', edit_customer_order_path(@customer_order) %> |
	<%= link_to 'Back', customer_orders_path %> |
<% end %>
<%= link_to 'Account', root_path %>